### ISSUE TITLE
Thunder.java

### ISSUE THREAD

**Issue by gglerum** [Katsukari/Homework#3]
Technisch in order. Alleen qua gebruiksvriendelijkheid zou ik de gebruiker eerder de feedback teruggeven dat zij geen juiste `unit` heeft gekozen. Nu krijg je de feedback pas nadat je de aantal seconden hebt opgegeven.

Wat ik mijzelf afvraag is of windsnelheid invloed heeft op het verplaatsen van de onweersbui. De formule die hier altijd voor gebruikt wordt gaat namelijk alleen uit van de snelheid van het geluid, wat volgens mij een constante is. Als namelijk windsnelheid invloed heeft, dan klopt de meting van deze applicatie niet, en zul je om twee meet moment moeten vragen.

De enige aanpassing die nodig is, is het terug geven van feedback over verkeerde invoer van de `unit` aan de gebruiker. De rest zou ik zo laten.

**Comment by Katsukari** [comment]
Ik had de feedback daarop verkeerd neergezet waardoor het nooit kon runnen. Dit is nu gefixt en ik heb de unit of measurement prompt in de loop verplaatst.
