### ISSUE TITLE
AddingPerson.java

### ISSUE THREAD

**Issue by gglerum** [Katsukari/Homework#4]
https://github.com/Katsukari/Homework/blob/470a9a5012013be3c69a539e867b2aeebc30e7e4/src/main/java/nl/Katsukari/AddingPerson.java#L7

Elke class graag in zijn eigen bestand. Cursor op de class naam `Person` zetten en dan `F6`.

https://github.com/Katsukari/Homework/blob/470a9a5012013be3c69a539e867b2aeebc30e7e4/src/main/java/nl/Katsukari/AddingPerson.java#L36-L39

De variabel `running` wordt eigenlijk maar op drie plaatsen gebruikt. Één keer voor initializatie, één keer voor het zetten naar een andere waarden en één keer om uit te lezen. Dit zijn variabelen waarbij je je mag afvragen of je een andere oplossing kan gebruiken. In dit scenario mag je namelijk ook direct `true` gebruiken in je while loop zoals je dat op regel [72](https://github.com/Katsukari/Homework/blob/470a9a5012013be3c69a539e867b2aeebc30e7e4/src/main/java/nl/Katsukari/AddingPerson.java#L72) doet. Dan kun je zoals op regel [53](https://github.com/Katsukari/Homework/blob/470a9a5012013be3c69a539e867b2aeebc30e7e4/src/main/java/nl/Katsukari/AddingPerson.java#L53) een `return` gebruiken bij [case 4](https://github.com/Katsukari/Homework/blob/470a9a5012013be3c69a539e867b2aeebc30e7e4/src/main/java/nl/Katsukari/AddingPerson.java#L97). Dan wordt de `running` variabel overbodig.

https://github.com/Katsukari/Homework/blob/470a9a5012013be3c69a539e867b2aeebc30e7e4/src/main/java/nl/Katsukari/AddingPerson.java#L71-L84

Dit is mijn fout. De waarschuwing die je krijgt m.b.t. een exception komt omdat `continue` wordt gebruikt in plaats van `break`. Hierdoor blijft de `while` loop zich steeds weer herhalen i.p.v. dat hij wordt beëindigt. Als je dit aanpast heb je ook een `break` nodig om je `case` af te sluiten, anders gaat het programma direct door naar `case 3` (wat misschien niet eens zo'n gekke feature is).

https://github.com/Katsukari/Homework/blob/470a9a5012013be3c69a539e867b2aeebc30e7e4/src/main/java/nl/Katsukari/AddingPerson.java#L109-L113

https://github.com/Katsukari/Homework/blob/470a9a5012013be3c69a539e867b2aeebc30e7e4/src/main/java/nl/Katsukari/AddingPerson.java#L76

Mooi gebruik van een lambda! Mocht dit een suggestie zijn geweest van IntelliJ, lees dan nog even goed na hoe lambda's precies werken. 

Voor elke keer dat je `askForInput` aanroept maak je een nieuw object van de Scanner class aan. Deze mag je boven in de `AddingPerson` class declareren met assignment. Je kunt het zelfde object voor elke vraag her gebruiken. 

Één laatste opmerking: `optie 0`, doet precies hetzelfde als  `optie 4` met als enige uitzondering het printen van `Exiting...`. Was dit de bedoeling?

**Comment by Katsukari** [comment]
1. Person zit nu in een apart bestand.

2. Running is weggehaald, nu alleen while (true). Break statements zijn toegevoegd.

3. Case 2 is gefixt nu als het goed is. En ik heb de feature van case 2 -> 3 behouden ;)

4. Ik heb lambda speciafiek gebruikt, geen zorgen. Hier had ik me al voor ingelezen.

5. Scanner is verplaatst naar boven en werkt.

6. Nee dat was totaal niet de bedoeling! Dit is nu ook gefixt.
